### ISSUE TITLE
Regarding the LLC4320 grid variables

### ISSUE THREAD

**Issue by SLYpma** [MITgcm/xmitgcm#207] opened 2020-06-16 14:15 UTC
For our research purposes we want to save surface velocity output from the LLC4320 of only a small region (at the equator) to our local computer as netcdf, preferably using the lon/lat coordinates (as in XG, YG, XC, YC). However, using: 
`ds = model.get_dataset(varnames=['U','V'], iter_start=time_index, iter_stop=time_index+1, k_levels=[0], read_grid = True)`
I only seem to get access to the XC and YC coordinates. How should I interpret the coordinates of U and V (i, j, i_g and j_g)? Can I create the XG and YG coordinates myself (assuming a C-grid), or do I need to do something else?

**Comment by rabernat** [comment] 2020-06-17 20:36
Thanks for your question @SLYpma. We just added this capability in #197, so there may be some bugs to work out.

I tried to translate your question into a reproducible code example:
```python
from xmitgcm import llcreader
model = llcreader.known_models.ECCOPortalLLC4320Model()
time_index = model.iter_start
ds = model.get_dataset(varnames=['U','V'], iter_start=time_index, iter_stop=time_index+1, k_levels=[0], read_grid = True)
print(ds)
```

I see
```
<xarray.Dataset>
Dimensions:  (face: 13, i: 4320, i_g: 4320, j: 4320, j_g: 4320, k: 1, k_l: 1, k_p1: 2, k_u: 1, time: 1)
Coordinates:
  * face     (face) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
  * i        (i) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * i_g      (i_g) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * j        (j) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * j_g      (j_g) int64 0 1 2 3 4 5 6 7 ... 4313 4314 4315 4316 4317 4318 4319
  * k        (k) int64 0
  * k_u      (k_u) int64 0
  * k_l      (k_l) int64 0
  * k_p1     (k_p1) int64 0 1
    niter    (time) int64 ...
  * time     (time) datetime64[ns] 2011-09-13
    CS       (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    SN       (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    Depth    (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    drC      (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    drF      (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    dxC      (face, j, i_g) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    dxF      (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    dxG      (face, j_g, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    dyC      (face, j_g, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    dyF      (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    dyG      (face, j, i_g) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    hFacC    (k, face, j, i) float32 dask.array<chunksize=(1, 3, 4320, 4320), meta=np.ndarray>
    hFacS    (k, face, j_g, i) float32 dask.array<chunksize=(1, 3, 4320, 4320), meta=np.ndarray>
    hFacW    (k, face, j, i_g) float32 dask.array<chunksize=(1, 3, 4320, 4320), meta=np.ndarray>
    PHrefC   (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    PHrefF   (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    rA       (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    rAs      (face, j_g, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    rAw      (face, j, i_g) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    Z        (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zp1      (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    rhoRef   (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    XC       (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    YC       (face, j, i) float32 dask.array<chunksize=(3, 4320, 4320), meta=np.ndarray>
    Zl       (k_l) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zu       (k_u) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
Data variables:
    U        (time, k, face, j, i_g) float32 dask.array<chunksize=(1, 1, 3, 4320, 4320), meta=np.ndarray>
    V        (time, k, face, j_g, i) float32 dask.array<chunksize=(1, 1, 3, 4320, 4320), meta=np.ndarray>
```

You're correct that `XG` and `YG` appear to be missing. It looks like they were not included in this list:

https://github.com/MITgcm/xmitgcm/blob/3ab1fdba44c9c2a216a863df604039eee6132dca/xmitgcm/llcreader/known_models.py#L65-L71

I tried to hack around this as follows:
```python
model.grid_varnames += ['XG', 'YG']
ds = model.get_dataset(varnames=['U','V'], iter_start=time_index, iter_stop=time_index+1, k_levels=[0], read_grid = True)
```

But I hit the error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-b75739a94ec7> in <module>
----> 1 ds = model.get_dataset(varnames=['U','V'], iter_start=time_index, iter_stop=time_index+1, k_levels=[0], read_grid = True)
      2 print(ds)

~/Code/xmitgcm/xmitgcm/llcreader/llcmodel.py in get_dataset(self, varnames, iter_start, iter_stop, iter_step, k_levels, k_chunksize, type, read_grid, grid_vars_to_coords)
    743         for vname in grid_varnames:
    744             my_k_levels = k_levels if _VAR_METADATA[vname]['dims'] !=['k_p1'] else kp1_levels
--> 745             grid_facets[vname] = self._get_facet_data(vname, None, my_k_levels, k_chunksize)
    746 
    747         # transform it into faces or latlon

~/Code/xmitgcm/xmitgcm/llcreader/llcmodel.py in _get_facet_data(self, varname, iters, klevels, k_chunksize)
    645 
    646     def _get_facet_data(self, varname, iters, klevels, k_chunksize):
--> 647         mask, index = self._get_mask_and_index_for_variable(varname)
    648         # needs facets to be outer index of nested lists
    649         dims = _VAR_METADATA[varname]['dims']

~/Code/xmitgcm/xmitgcm/llcreader/llcmodel.py in _get_mask_and_index_for_variable(self, vname)
    582             point = 's'
    583         elif 'i_g' in dims and 'j_g' in dims:
--> 584             raise ValueError("Don't have masks for corner points!")
    585         else:
    586             # this is not a 2D variable

ValueError: Don't have masks for corner points!
```

@timothyas - did you encounter this while working on #197? Any reason you didn't include `XG` and `YG` in the grid variables?

**Comment by rabernat** [comment] 2020-06-18 02:32
@SLYpma - your problem should be fixed if you install the latest version of xmitgcm from github:

```
pip install git+https://github.com/MITgcm/xmitgcm.git
```

**Closed** 2020-06-18 02:31 UTC

**Comment by SLYpma** [comment] 2020-06-18 06:44
great, they are there now! Thank you @rabernat !!
